Migrate to vtex.css-handles@1.x
vtex-apps/menu pull request #120
Opened 2020-12-09 17:44 UTC by victorhmp

#### What problem is this solving?

#### How to test it?

[Workspace](Link goes here!)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-12-09 20:39 UTC, kaisermann approved these changes

2020-12-09 20:39 UTC, kaisermann commented on docs/README.md
> +| `classes`         | `CustomCSSClasses` | Used to override default CSS handles. To better understand how this prop works, we recommend reading about it [here](https://github.com/vtex-apps/css-handle
```suggestion
| `classes`         | `CustomCSSClasses` | Used to override default CSS handles. To better understand how this prop works, we recommend reading about it [here](https://github.com/vtex-apps/css-handles#usecustomclasses). Note that this is only useful if you're importing this block as a React component.                                      | `undefined`           |
```

2020-12-09 20:39 UTC, kaisermann commented on react/SubmenuAccordion.tsx
> -        className={classNames(handles.submenuAccordion, 'w-100 flex pl4 flex')}
Caraca que ódio AHAHAHAHAH

2020-12-09 20:47 UTC, vitorflg approved these changes

2020-12-09 20:52 UTC, klzns approved these changes

2020-12-15 14:47 UTC, icazevedo requested changes

2020-12-15 14:47 UTC, icazevedo commented on react/Column.tsx
> +  classes: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```suggestion
  classes?: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```

2020-12-15 14:47 UTC, icazevedo commented on react/Menu.tsx
> +  classes: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```suggestion
  classes?: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```

2020-12-15 14:47 UTC, icazevedo commented on react/MenuItem.tsx
> +  classes: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```suggestion
  classes?: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```

2020-12-15 14:47 UTC, icazevedo commented on react/Submenu.tsx
> +  classes: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```suggestion
  classes?: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```

2020-12-15 14:47 UTC, icazevedo commented on react/SubmenuAccordion.tsx
> +  classes: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```suggestion
  classes?: CssHandlesTypes.CustomClasses<typeof CSS_HANDLES>
```

2020-12-15 14:47 UTC, icazevedo commented on react/index.tsx
> +  const { handles } = useCssHandles(CSS_HANDLES)
Is there a reason why this component doesn't have `classes`?

2020-12-15 14:47 UTC, icazevedo commented on react/components/StyledLink.tsx
> +  const { handles, withModifiers } = useCssHandles(CSS_HANDLES)
Is there a reason why this component doesn't have classes?

2020-12-15 14:50 UTC, icazevedo requested changes

2020-12-15 14:50 UTC, icazevedo commented on react/Submenu.tsx
> +  const { handles, withModifiers } = useCssHandles(CSS_HANDLES)
I think you forgot to use the `classes` prop here

2020-12-18 15:14 UTC, guerreirobeatriz approved these changes

2020-12-22 17:17 UTC, victorhmp commented on react/index.tsx
> +  const { handles } = useCssHandles(CSS_HANDLES)
Yep, I forgot 😂

2020-12-22 17:29 UTC, victorhmp commented on react/components/StyledLink.tsx
> +  const { handles, withModifiers } = useCssHandles(CSS_HANDLES)
Yep, because this component is not exported by the app

2020-12-22 17:30 UTC, victorhmp commented on react/Submenu.tsx
> +  const { handles, withModifiers } = useCssHandles(CSS_HANDLES)
Good catch!

2020-12-23 14:03 UTC, icazevedo approved these changes

2021-01-04 18:07 UTC, merged