feat: Change menu item title  name with editorItemTitle
vtex-apps/menu pull request #130
Opened 2021-04-16 20:54 UTC by iago1501

#### What problem is this solving?

Menu Items created on site editor with the same name as "item"

![image](https://user-images.githubusercontent.com/13649073/115081444-a8623680-9eda-11eb-8cf1-5a1173515369.png)

Added the user's possibility to change this with __editorItemTitle field 

![image](https://user-images.githubusercontent.com/13649073/115081590-ed866880-9eda-11eb-9816-32abee699a75.png)

#### How to test it?

Go to the [Workspace](https://itemtitle--storecomponents.myvtex.com/admin/cms/site-editor)

Try to add a new menu item here: 

![image](https://user-images.githubusercontent.com/13649073/115081767-34745e00-9edb-11eb-9b53-c3746425cbc8.png)

![image](https://user-images.githubusercontent.com/13649073/115081804-40f8b680-9edb-11eb-9efe-5c6ffc0b5f9f.png)

Fill Menu Item Name's field, go back, and check if the menu item name created is the same

![image](https://user-images.githubusercontent.com/13649073/115081957-7bfaea00-9edb-11eb-8c5d-50fec380b8ed.png)

#### Related to / Depends on

Zendesk KI: #342030

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/3otPoIR7tGymabNvS8/giphy.gif)

2021-04-16 21:15 UTC, klzns commented on messages/en.json
> +  "admin/editor.menu.item.editorItemTitle.description": "This will only be visible on site editor",
```suggestion
  "admin/editor.menu.item.editorItemTitle.description": "This will only be visible on Site Editor",
```

2021-04-16 21:16 UTC, klzns approved these changes

2021-04-19 14:23 UTC, clara-cruz requested changes
For ES, I suggest:
  "admin/editor.menu.item.editorItemTitle.title": "Nombre del Elemento del menú",
  "admin/editor.menu.item.editorItemTitle.description": "Esto solo será visible en Site Editor",

2021-04-19 14:57 UTC, iago1501 commented
> For ES, I suggest:
> "admin/editor.menu.item.editorItemTitle.title": "Nombre del Elemento del menú",
> "admin/editor.menu.item.editorItemTitle.description": "Esto solo será visible en Site Editor",

Did it ✌🏻

2021-04-19 15:29 UTC, clara-cruz approved these changes

2021-04-20 17:51 UTC, iago1501 commented
@vtex-apps/localization can you help me here with Japanese and also Romanian, please? 🙏🏻

2021-04-20 19:20 UTC, camilavcoutinho approved these changes
All Good! RO and JP ✨

2021-04-22 13:49 UTC, merged

2022-02-25 03:16 UTC, RamonSouzaRibeiro commented
Great feature!
But I have a question, when I have some item with "ui:widget": "image-uploader", the image overwrite the title.

Example:
![image](https://user-images.githubusercontent.com/97455209/155646482-1107bd12-eb11-4728-bb1e-2119c7386784.png)

Is there something I can do to use the __editorItemTitle in this cases?

2022-04-29 20:08 UTC, martinlariaspaz commented
> Great feature! But I have a question, when I have some item with "ui:widget": "image-uploader", the image overwrite the title.
> 
> Example: ![image](https://user-images.githubusercontent.com/97455209/155646482-1107bd12-eb11-4728-bb1e-2119c7386784.png)
> 
> Is there something I can do to use the __editorItemTitle in this cases?

I need to know this too.