SVG icon from Site Editor
vtex-apps/menu pull request #141
Opened 2021-08-08 22:32 UTC by IvanLopezLuna

#### What problem is this solving?
Be able to edit the SVG icon from Site Editor. Currently, to change an icon it is necessary to do it from the theme app.

This is useful for not repeating different `menu` or `menu-item` blocks in the .jsonc files just to change the icon, instead, it is possible to have only one general block and do all customization from Site Editor. This will also make site maintenance easier.

#### How to test it?
[Workspace / Site Editor](https://dev--martimxlite.myvtex.com/admin/cms/site-editor)
1. Use Mobile view
2. Click on hamburguer menu icon
3. Select any menu item (menu-item or menu)
4. Edit the menu item
5. Change the id of svg icon (Icon Props: ID) by `svgIcon-house`

#### Screenshots or example usage:
![Screenshot_20210808-171647](https://user-images.githubusercontent.com/23274114/128647561-62860db8-b5f4-46f0-b28e-4468060772fc.jpg)
![Screenshot_20210808-171705](https://user-images.githubusercontent.com/23274114/128647393-7c13d4c0-92b1-4b65-8ce5-bf718c1468ce.jpg)

#### How does this PR make you feel? [:link:](http://giphy.com/)
![](https://media.giphy.com/media/D7z8JfNANqahW/giphy.gif)

2021-08-30 18:15 UTC, victorhmp requested changes
Hi @IvanLopezLuna !
Thanks for the PR, it looks great! But I have an alternate solution to this, tell me what you think about it.

What if instead of adding a new property in the Site Editor, which might confuse users since there's already an `Icon ID` prop there, we simply update the code to take that prop into consideration? Something like:
- If `iconProps.id` is received by the component (via props or `.json` files), then just use this value;
- If `iconProps.id` is **not**  received by the component, but `iconId` is, then just use `iconId` on line 65.

Currently, it seems like the component is just ignoring `iconId`, right? Then we can use it as an alias to `iconProps.id`, keeping the user experience in the Site Editor the same :)

2021-08-30 18:15 UTC, victorhmp commented on store/contentSchemas.json
> +                    },
Use message IDs from the `messages` folder so that these strings (both `title`s) are translated to all languages supported in the admin.

2021-08-30 18:15 UTC, victorhmp commented on CHANGELOG.md
> +
```suggestion
```

2021-09-02 03:12 UTC, IvanLopezLuna commented
Hi @victorhmp!
Your suggestions were implemented and I think that the improvement is better now.

2021-09-03 17:53 UTC, victorhmp approved these changes
LGTM

2021-09-06 13:31 UTC, igorbrasileiro approved these changes
Nice job, @IvanLopezLuna 👏  !!

2021-09-13 18:53 UTC, merged