Fix submenu staying open if the mouse leaves the menu
vtex-apps/menu pull request #169
Opened 2022-08-30 01:13 UTC by ivanlopezluna

#### What problem is this solving?
Some cases, when the mouse leaves the parent item, the submenu remains open. This is common if the user moves from the menu to address bar or browser tab, also when it is combined with scrolldown.

#### How to test it?
[Workspace](https://storeframeworkdev--tafmxqa.myvtex.com/)

#### Screenshots or example usage:
**Before**

https://user-images.githubusercontent.com/23274114/187324819-1258d9ad-43fc-4cc8-abbd-d75c5365aec4.mp4

**After**

https://user-images.githubusercontent.com/23274114/187324739-5796c65d-c3d9-41c5-ae14-7ee605c048a7.mp4

#### Related to
PR: https://github.com/vtex-apps/menu/pull/108

2022-10-06 20:01 UTC, danzanzini requested changes
Hey @IvanLopezLuna. Thanks for the contribution. 

Left one comment regarding this new prop. Why not use the maxSpeed instead of a new prop?

2022-10-06 20:01 UTC, danzanzini commented on react/hooks/useMouseSpeedDebouncer.ts
> +      } else if (lastSpeed !== null && lastSpeed >= minUnusualSpeed) {
Why not use the maxSpeed also here?
```suggestion
      } else if (lastSpeed !== null && lastSpeed > maxSpeed) {
```

2022-10-16 21:32 UTC, IvanLopezLuna commented on react/hooks/useMouseSpeedDebouncer.ts
> +      } else if (lastSpeed !== null && lastSpeed >= minUnusualSpeed) {
Hi @danzanzini! 

You are right, it is a better approach. The change was made, thanks!

2022-11-17 14:32 UTC, filipewl requested changes
Looking good @IvanLopezLuna!

I believe @danzanzini's [review](https://github.com/vtex-apps/menu/pull/169#pullrequestreview-1133569142) suggestions have already been addressed. Maybe he just hasn't seen it yet, to remove his "requested changes" block.

I noticed one minor, but important, issue with where the description of the changes was placed in the `CHANGELOG.md` file, so I'm going to leave another change request. 

I'll be watching this PR closely from now on so we can proceed faster!

2022-11-17 14:32 UTC, filipewl commented on CHANGELOG.md
> +
Hey @IvanLopezLuna!

Could you please move the added lines under the `## [Unreleased]` line?

2022-11-21 18:10 UTC, IvanLopezLuna commented on CHANGELOG.md
> +
Hi @filipewl!

The last requested change it's done.

Thanks for you follow up!

2022-11-29 17:16 UTC, filipewl approved these changes
Thanks for addressing [my review](https://github.com/vtex-apps/menu/pull/169#pullrequestreview-1184413315)! I'm going to approve this now.

However, due to some internal policies related to the Black Friday season, we cannot deploy this right now. Once the permission to deploy is lifted, we'll merge and deploy this. This should happen in the next few days. I'll keep a close eye on this so we can merge as soon as possible. 

Thank you for your patience!

2022-12-06 17:03 UTC, filipewl approved these changes
Deploying this now. Thank you for your patience!

2022-12-06 17:04 UTC, merged